"use client";

/**
 * FinancialsTable Component
 * Displays financial facts, valuation, growth, and profitability metrics
 * with tooltips and color-coded favorable/unfavorable values.
 *
 * Requirements: 8.1, 8.2, 8.3, 8.4, 8.5, 8.6
 */

import { FinancialData } from "@/types";
import { useTheme } from "@/lib/theme-context";
import { useState } from "react";

export interface FinancialsTableProps {
  financials: FinancialData | null | undefined;
}

type Favorability = "favorable" | "unfavorable" | "neutral";

interface MetricItem {
  label: string;
  value: string;
  tooltip: string;
  favorability: Favorability;
}

interface MetricSection {
  title: string;
  tooltip: string;
  metrics: MetricItem[];
}

function getFavorabilityColors(favorability: Favorability, isDark: boolean) {
  switch (favorability) {
    case "favorable":
      return {
        text: isDark ? "text-green-400" : "text-green-600",
        badge: isDark
          ? "bg-green-900/60 text-green-300"
          : "bg-green-100 text-green-700",
      };
    case "unfavorable":
      return {
        text: isDark ? "text-red-400" : "text-red-600",
        badge: isDark
          ? "bg-red-900/60 text-red-300"
          : "bg-red-100 text-red-700",
      };
    case "neutral":
    default:
      return {
        text: isDark ? "text-gray-300" : "text-gray-700",
        badge: isDark
          ? "bg-gray-700 text-gray-300"
          : "bg-gray-100 text-gray-600",
      };
  }
}

function formatCurrency(value: number): string {
  if (Math.abs(value) >= 1e12) return `$${(value / 1e12).toFixed(2)}T`;
  if (Math.abs(value) >= 1e9) return `$${(value / 1e9).toFixed(2)}B`;
  if (Math.abs(value) >= 1e6) return `$${(value / 1e6).toFixed(2)}M`;
  return `$${value.toFixed(2)}`;
}

function formatPercent(value: number): string {
  return `${(value * 100).toFixed(2)}%`;
}

function formatRatio(value: number): string {
  return value.toFixed(2);
}

function getMarginFavorability(value: number): Favorability {
  if (value > 0.15) return "favorable";
  if (value < 0.05) return "unfavorable";
  return "neutral";
}

function getPERatioFavorability(value: number): Favorability {
  if (value <= 0) return "unfavorable";
  if (value < 20) return "favorable";
  if (value > 40) return "unfavorable";
  return "neutral";
}

function getPBRatioFavorability(value: number): Favorability {
  if (value <= 0) return "unfavorable";
  if (value < 3) return "favorable";
  if (value > 5) return "unfavorable";
  return "neutral";
}

function getPEGRatioFavorability(value: number): Favorability {
  if (value <= 0) return "unfavorable";
  if (value < 1) return "favorable";
  if (value > 2) return "unfavorable";
  return "neutral";
}

function getGrowthFavorability(value: number): Favorability {
  if (value > 0.1) return "favorable";
  if (value < 0) return "unfavorable";
  return "neutral";
}

function getROEFavorability(value: number): Favorability {
  if (value > 0.15) return "favorable";
  if (value < 0.05) return "unfavorable";
  return "neutral";
}

function getROAFavorability(value: number): Favorability {
  if (value > 0.05) return "favorable";
  if (value < 0.02) return "unfavorable";
  return "neutral";
}

function buildSections(data: FinancialData): MetricSection[] {
  return [
    {
      title: "Key Financial Facts",
      tooltip:
        "Core financial figures that summarize a company's size and profitability. Revenue is total sales, net income is profit after all expenses, and profit margin shows what percentage of revenue becomes profit.",
      metrics: [
        {
          label: "Revenue",
          value: formatCurrency(data.keyFacts.revenue),
          tooltip:
            "Total revenue generated by the company over the most recent reporting period. Higher revenue generally indicates a larger business. Green if positive, red if negative.",
          favorability: data.keyFacts.revenue > 0 ? "favorable" : "unfavorable",
        },
        {
          label: "Net Income",
          value: formatCurrency(data.keyFacts.netIncome),
          tooltip:
            "The company's total profit after subtracting all expenses, taxes, and costs. Green if positive (profitable), red if negative (loss-making).",
          favorability:
            data.keyFacts.netIncome > 0 ? "favorable" : "unfavorable",
        },
        {
          label: "Profit Margin",
          value: formatPercent(data.keyFacts.profitMargin),
          tooltip:
            "The percentage of revenue that becomes profit. Green above 15% (strong), red below 5% (weak), gray in between.",
          favorability: getMarginFavorability(data.keyFacts.profitMargin),
        },
      ],
    },
    {
      title: "Valuation Metrics",
      tooltip:
        "Ratios that help assess whether a stock is priced fairly relative to its earnings, book value, and growth. Lower ratios may suggest better value.",
      metrics: [
        {
          label: "P/E Ratio",
          value: formatRatio(data.valuation.peRatio),
          tooltip:
            "Price-to-Earnings ratio compares the stock price to earnings per share. Green below 20 (potentially undervalued), red above 40 (potentially overvalued) or negative, gray in between.",
          favorability: getPERatioFavorability(data.valuation.peRatio),
        },
        {
          label: "P/B Ratio",
          value: formatRatio(data.valuation.pbRatio),
          tooltip:
            "Price-to-Book ratio compares the stock price to the company's book value per share. Green below 3 (reasonable valuation), red above 5 or negative, gray in between.",
          favorability: getPBRatioFavorability(data.valuation.pbRatio),
        },
        {
          label: "PEG Ratio",
          value: formatRatio(data.valuation.pegRatio),
          tooltip:
            "Price/Earnings-to-Growth ratio factors in expected earnings growth. Green below 1 (undervalued relative to growth), red above 2 or negative, gray in between.",
          favorability: getPEGRatioFavorability(data.valuation.pegRatio),
        },
      ],
    },
    {
      title: "Growth Metrics",
      tooltip:
        "Measures of how quickly the company is expanding its revenue and earnings. Positive growth indicates the business is expanding.",
      metrics: [
        {
          label: "Revenue Growth",
          value: formatPercent(data.growth.revenueGrowth),
          tooltip:
            "Year-over-year percentage change in revenue. Green above 10% (strong growth), red if negative (declining), gray between 0–10%.",
          favorability: getGrowthFavorability(data.growth.revenueGrowth),
        },
        {
          label: "Earnings Growth",
          value: formatPercent(data.growth.earningsGrowth),
          tooltip:
            "Year-over-year percentage change in earnings. Green above 10% (strong growth), red if negative (declining), gray between 0–10%.",
          favorability: getGrowthFavorability(data.growth.earningsGrowth),
        },
      ],
    },
    {
      title: "Profitability Metrics",
      tooltip:
        "Ratios that measure how effectively the company generates profit from its equity, assets, and operations.",
      metrics: [
        {
          label: "ROE",
          value: formatPercent(data.profitability.roe),
          tooltip:
            "Return on Equity measures how effectively the company uses shareholder equity to generate profit. Green above 15% (strong), red below 5% (weak), gray in between.",
          favorability: getROEFavorability(data.profitability.roe),
        },
        {
          label: "ROA",
          value: formatPercent(data.profitability.roa),
          tooltip:
            "Return on Assets measures how efficiently the company uses its total assets to generate profit. Green above 5% (good), red below 2% (weak), gray in between.",
          favorability: getROAFavorability(data.profitability.roa),
        },
        {
          label: "Operating Margin",
          value: formatPercent(data.profitability.operatingMargin),
          tooltip:
            "The percentage of revenue remaining after paying operating expenses. Green above 15% (efficient), red below 5% (thin margins), gray in between.",
          favorability: getMarginFavorability(
            data.profitability.operatingMargin
          ),
        },
      ],
    },
  ];
}

export function FinancialsTable({ financials }: FinancialsTableProps) {
  const { resolvedTheme } = useTheme();
  const isDark = resolvedTheme === "dark";

  if (!financials) {
    return (
      <div
        className={`p-6 rounded-lg shadow-sm ${isDark ? "bg-gray-800" : "bg-white"}`}
      >
        <h2
          className={`text-lg font-semibold mb-4 ${isDark ? "text-white" : "text-gray-900"}`}
        >
          Financials
        </h2>
        <div className="space-y-4">
          {[1, 2, 3, 4].map((i) => (
            <div
              key={i}
              className={`h-24 rounded-lg animate-pulse ${isDark ? "bg-gray-700" : "bg-gray-200"}`}
            />
          ))}
        </div>
      </div>
    );
  }

  const sections = buildSections(financials);

  return (
    <div
      className={`p-4 sm:p-6 lg:p-8 rounded-lg shadow-sm ${isDark ? "bg-gray-800" : "bg-white"}`}
      role="region"
      aria-label="Financial data"
    >
      <h2
        className={`text-lg font-semibold mb-4 sm:mb-6 ${isDark ? "text-white" : "text-gray-900"}`}
      >
        Financials
      </h2>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-6 lg:gap-8">
        {sections.map((section) => (
          <SectionCard key={section.title} section={section} isDark={isDark} />
        ))}
      </div>
    </div>
  );
}

interface SectionCardProps {
  section: MetricSection;
  isDark: boolean;
}

function SectionCard({ section, isDark }: SectionCardProps) {
  const [showSectionTooltip, setSectionTooltip] = useState(false);

  return (
    <div
      className={`p-4 rounded-lg border ${
        isDark ? "bg-gray-700/50 border-gray-600" : "bg-gray-50 border-gray-200"
      }`}
    >
      <div
        className="relative flex items-center gap-2 cursor-help mb-3"
        onMouseEnter={() => setSectionTooltip(true)}
        onMouseLeave={() => setSectionTooltip(false)}
      >
        <h3
          className={`text-base font-semibold ${isDark ? "text-white" : "text-gray-900"}`}
        >
          {section.title}
        </h3>
        <span
          className={`flex-shrink-0 w-5 h-5 rounded-full flex items-center justify-center text-xs ${
            isDark ? "bg-gray-600 text-gray-300" : "bg-gray-200 text-gray-600"
          }`}
        >
          ?
        </span>
        {showSectionTooltip && (
          <div
            className={`absolute z-10 w-64 p-3 rounded-lg shadow-lg text-sm ${
              isDark
                ? "bg-gray-900 text-gray-200 border border-gray-700"
                : "bg-white text-gray-700 border border-gray-200"
            }`}
            style={{ top: "calc(100% + 6px)", left: 0 }}
          >
            {section.tooltip}
          </div>
        )}
      </div>

      <div className="space-y-2">
        {section.metrics.map((metric) => (
          <MetricRow key={metric.label} metric={metric} isDark={isDark} />
        ))}
      </div>
    </div>
  );
}

interface MetricRowProps {
  metric: MetricItem;
  isDark: boolean;
}

function MetricRow({ metric, isDark }: MetricRowProps) {
  const [showTooltip, setShowTooltip] = useState(false);
  const colors = getFavorabilityColors(metric.favorability, isDark);

  return (
    <div
      className={`flex items-center justify-between py-2 border-b last:border-b-0 ${
        isDark ? "border-gray-600" : "border-gray-200"
      }`}
    >
      <div className="relative flex items-center gap-2">
        <span
          className={`text-sm ${isDark ? "text-gray-300" : "text-gray-600"}`}
        >
          {metric.label}
        </span>
        <button
          type="button"
          className={`flex-shrink-0 w-4 h-4 rounded-full flex items-center justify-center text-[10px] cursor-help
            focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 ${
              isDark ? "bg-gray-600 text-gray-300" : "bg-gray-200 text-gray-600"
            }`}
          aria-label={`More info about ${metric.label}`}
          onMouseEnter={() => setShowTooltip(true)}
          onMouseLeave={() => setShowTooltip(false)}
          onFocus={() => setShowTooltip(true)}
          onBlur={() => setShowTooltip(false)}
        >
          ?
        </button>
        {showTooltip && (
          <div
            role="tooltip"
            className={`absolute z-10 w-64 p-3 rounded-lg shadow-lg text-sm ${
              isDark
                ? "bg-gray-900 text-gray-200 border border-gray-700"
                : "bg-white text-gray-700 border border-gray-200"
            }`}
            style={{ top: "calc(100% + 6px)", left: 0 }}
          >
            {metric.tooltip}
          </div>
        )}
      </div>
      <span className={`text-sm font-mono font-semibold ${colors.text}`}>
        {metric.value}
      </span>
    </div>
  );
}
